version: "3.9"
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: base-project
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
