CREATE TABLE usuarios (
    id_usuario       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR2(50) NOT NULL,
    apellido         VARCHAR2(50) NOT NULL,
    fecha_nacimiento DATE,
    telefono         VARCHAR2(20),
    direccion        VARCHAR2(150)
);

INSERT INTO usuarios (nombre, apellido, fecha_nacimiento, telefono, direccion)
VALUES ('Juan', 'Pérez', TO_DATE('1990-05-12','YYYY-MM-DD'), '555123456', 'Calle Falsa 123');

INSERT INTO usuarios (nombre, apellido, fecha_nacimiento, telefono, direccion)
VALUES ('María', 'Gómez', TO_DATE('1985-11-23','YYYY-MM-DD'), '555987654', 'Avenida Siempre Viva 456');

INSERT INTO usuarios (nombre, apellido, fecha_nacimiento, telefono, direccion)
VALUES ('Carlos', 'López', TO_DATE('1992-07-15','YYYY-MM-DD'), '555111222', 'Calle Luna 78');

INSERT INTO usuarios (nombre, apellido, fecha_nacimiento, telefono, direccion)
VALUES ('Ana', 'Martínez', TO_DATE('1988-02-28','YYYY-MM-DD'), '555333444', 'Plaza Mayor 5');

INSERT INTO usuarios (nombre, apellido, fecha_nacimiento, telefono, direccion)
VALUES ('Luis', 'Ramírez', TO_DATE('1995-09-10','YYYY-MM-DD'), '555555666', 'Calle Sol 22');

INSERT INTO usuarios (nombre, apellido, fecha_nacimiento, telefono, direccion)
VALUES ('Sofía', 'Torres', TO_DATE('1991-12-01','YYYY-MM-DD'), '555777888', 'Avenida del Mar 9');

INSERT INTO usuarios (nombre, apellido, fecha_nacimiento, telefono, direccion)
VALUES ('Miguel', 'Hernández', TO_DATE('1989-03-20','YYYY-MM-DD'), '555999000', 'Calle Verde 14');

INSERT INTO usuarios (nombre, apellido, fecha_nacimiento, telefono, direccion)
VALUES ('Laura', 'Vargas', TO_DATE('1993-08-18','YYYY-MM-DD'), '555121212', 'Avenida Central 33');

INSERT INTO usuarios (nombre, apellido, fecha_nacimiento, telefono, direccion)
VALUES ('Diego', 'Santos', TO_DATE('1994-06-05','YYYY-MM-DD'), '555343434', 'Calle Naranja 21');

INSERT INTO usuarios (nombre, apellido, fecha_nacimiento, telefono, direccion)
VALUES ('Elena', 'Ruiz', TO_DATE('1990-11-30','YYYY-MM-DD'), '555565656', 'Plaza Nueva 7');

COMMIT;
